# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
include:
  - board: nice_nano@2//zmk
    shield: donglex7x4x2_left
    snippet: studio-rpc-usb-uart
    artifact-name: donglex7x4x2_left_with_studio
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano@2//zmk
    shield: donglex7x4x2_right
    artifact-name: donglex7x4x2_right_with_studio
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano@2//zmk
    shield: donglex7x4x2_dongle
    snippet: studio-rpc-usb-uart
    artifact-name: donglex7x4x2_dongle_oled_3c
    cmake-args: -DDTC_OVERLAY_FILE=boards/shields/donglex7x4x2/donglex7x4x2_dongle_3c.overlay
  - board: nice_nano@2//zmk
    shield: donglex7x4x2_dongle
    snippet: studio-rpc-usb-uart
    artifact-name: donglex7x4x2_dongle_oled_3d
    cmake-args: -DDTC_OVERLAY_FILE=boards/shields/donglex7x4x2/donglex7x4x2_dongle_3d.overlay
  - board: nice_nano@2//zmk
    shield: settings_reset
    artifact-name: settings_reset
