# Enable ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# JIS
CONFIG_LAYOUT_SHIFT_TARGET_JIS=y # 日本語(JIS)レイアウト zmk-layout-shift

# Bluetoothの最大接続数とペアリング数
# 外部デバイス(5台) + 子機(左手・右手) = 7
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7
