# Enable ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# JIS
CONFIG_LAYOUT_SHIFT_TARGET_JIS=y # 日本語(JIS)レイアウト zmk-layout-shift

# Bluetooth device name length: "donglex7x4x2_ergo42" is 19 chars, must be < BT_DEVICE_NAME_MAX
CONFIG_BT_DEVICE_NAME_MAX=20

# Bluetooth Battery Service https://github.com/kot149/zmk-battery-center
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
